name: farmacap
description: Una aplicación para manejo de gastos de planes empresariales para compra de medicamentos.

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl:
  cupertino_icons: ^1.0.0
  kartal: ^1.2.0
  sqflite: ^1.3.0
  provider: ^4.3.3
  string_validator: ^0.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.8.1

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png"

flutter:
  uses-material-design: true

  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  fonts:
    - family: Ubuntu
      fonts:
        - asset: assets/fonts/ubuntu/Ubuntu-Bold.ttf
          weight: 700
        - asset: assets/fonts/ubuntu/Ubuntu-BoldItalic.ttf
          style: italic
          weight: 700
        - asset: assets/fonts/ubuntu/Ubuntu-Italic.ttf
          style: italic
        - asset: assets/fonts/ubuntu/Ubuntu-Light.ttf
          weight: 300
        - asset: assets/fonts/ubuntu/Ubuntu-LightItalic.ttf
          style: italic
          weight: 300
        - asset: assets/fonts/ubuntu/Ubuntu-Medium.ttf
          weight: 500
        - asset: assets/fonts/ubuntu/Ubuntu-MediumItalic.ttf
          style: italic
          weight: 500
        - asset: assets/fonts/ubuntu/Ubuntu-Regular.ttf
